require("leap").setup {
    max_phase_one_targets = nil,
    highlight_unlabeled_phase_one_targets = true,
    max_highlighted_traversal_targets = 50,
    case_sensitive = false,
    equivalence_classes = { " \t", "\r\n" },
    substitute_chars = { ["\r"] = "¬", ["\n"] = "¬" },

    safe_labels = { "s", "f", "n", "u", "t", "/", "S", "F", "N", "L", "H", "M", "U", "G", "T", "?", "Z" },
    labels = {
        "s",
        "f",
        "n",
        "j",
        "k",
        "l",
        "h",
        "o",
        "d",
        "w",
        "e",
        "m",
        "b",
        "u",
        "y",
        "v",
        "r",
        "g",
        "t",
        "c",
        "x",
        "/",
        "z",
        "S",
        "F",
        "N",
        "J",
        "K",
        "L",
        "H",
        "O",
        "D",
        "W",
        "E",
        "M",
        "B",
        "U",
        "Y",
        "V",
        "R",
        "G",
        "T",
        "C",
        "X",
        "?",
        "Z",
    },

    special_keys = {
        repeat_search = "]",
        next_phase_one_target = "[",
        next_target = { "<enter>", ";" },
        prev_target = { "<tab>", "," },
        next_group = "<space>",
        prev_group = "<tab>",
        multi_accept = "<enter>",
        multi_revert = "<backspace>",
    },
}
require("leap").add_default_mappings()

vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap-forward-to)")
vim.keymap.del({ "x", "o" }, "x")
vim.keymap.del({ "x", "o" }, "X")
vim.keymap.set({ "x", "o" }, "<leader>ft", "<Plug>(leap-forward-till)")
vim.keymap.set({ "x", "o" }, "<leader>bt", "<Plug>(leap-backward-till)")
